version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
  ignore:
  - dependency-name: Microsoft.Win32.Registry.AccessControl
    versions:
    - ">= 0"
  - dependency-name: Microsoft.Windows.Compatibility
    versions:
    - ">= 0"
  - dependency-name: System.*
    versions:
    - ">= 0"
- package-ecosystem: nuget
  directory: "/src/Modules"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
- package-ecosystem: nuget
  directory: "/test/tools/Modules"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
  ignore:
  - dependency-name: Microsoft.Win32.Registry.AccessControl
    versions:
    - ">= 0"
  - dependency-name: Microsoft.Windows.Compatibility
    versions:
    - ">= 0"
  - dependency-name: System.*
    versions:
    - ">= 0"
- package-ecosystem: nuget
  directory: "/tools/packaging/projects/reference/System.Management.Automation"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
  ignore:
  - dependency-name: Microsoft.Win32.Registry.AccessControl
    versions:
    - ">= 0"
  - dependency-name: Microsoft.Windows.Compatibility
    versions:
    - ">= 0"
  - dependency-name: System.*
    versions:
    - ">= 0"
- package-ecosystem: nuget
  directory: "/tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
  ignore:
  - dependency-name: Microsoft.Win32.Registry.AccessControl
    versions:
    - ">= 0"
  - dependency-name: Microsoft.Windows.Compatibility
    versions:
    - ">= 0"
  - dependency-name: System.*
    versions:
    - ">= 0"
